### ISSUE TITLE
Add a lock to the study when the study is already launched

### ISSUE THREAD

**Issue by MathildeFranconRTE** [AntaresSimulatorTeam/antares-xpansion#111]
Xpansion is able to run two separate studies at the same time, but xpansion must not be able to launch the same Antares study at the same time.

- Add a lock to the study when it is already launched  ? As soon as xpansion is launched, the generation of MPS and the updating of the Antares study at the end of the iterations should no longer be disrupted.

**Comment by sgatto** [comment]
We can put a lock to avoid that Xpansion uses the same study twice at the same time.
This would not avoid the Antares solver is launched against the same study by a standard Antares instance.
We should think about such a lock together with Antares_Simulator team.

**Comment by sgatto** [comment]
It can be implemented using a `lock` file

/!\ we need to be sure not to have non-catched exceptions in the python driver...
