### ISSUE TITLE
Modification on the gap of the algorithm

### ISSUE THREAD

**Issue by MathildeFranconRTE** [AntaresSimulatorTeam/antares-xpansion#116]
- Possibility to have a relative gap (percentage)

- Impose a minimum gap depending on the accuracy of the solvers (1e-6 ?)

- ~~Add a stopping criterion when the solution has not evolved for several iterations~~ moved to #268

**Comment by sgatto** [comment]
We might need to have a relative gap rather than an absolute one.
linked to #175

**Comment by sgatto** [comment]
we decided to remove this point and create a separate issue #268:

Add a stopping criterion when the solution has not evolved for several iterations
