### ISSUE TITLE
libjsoncpp-dev not a dependency

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/antares-xpansion#12]
Make json-dev mandatory at Makefile generation. If not installed, compilation fails because of missing header.

```
In file included from /home/florian/antares-xpansion/src/src_cpp/src_sequential/launcher.cpp:4:
/home/florian/antares-xpansion/src/src_cpp/src_sequential/JsonWriter.h:9:10: fatal error: json/writer.h: No such file or directory
    9 | #include <json/writer.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

```

**Comment by jmkerloch** [comment]
json_cpp should be available because we have a dependency in `sequentialcore` `CMakeLists.txt`

```
target_link_libraries (sequentialcore
	PUBLIC
		helpers
		jsoncpp_lib
)
```

and jsoncpp is required in root `CMakeLists.txt`

`find_package(jsoncpp CONFIG REQUIRED)`

Maybe `CONFIG REQUIRED` is incorrect and should be replaced with `REQUIRED `only

**Comment by jmkerloch** [comment]
Not reproductible on Ubuntu 20.04 in release/0.1 branch.
If `libjsoncpp-dev` is not installed, configure fail
