### ISSUE TITLE
INFEASIBLE master problem due to the Coin presolve

### ISSUE THREAD

**Issue by MathildeFranconRTE** [AntaresSimulatorTeam/antares-xpansion#120]
Master problem of iteration 85 of an OSMOSE study has been declared infeasible :

I0420 13:30:14.503019  6444 BendersFunctions.cpp:155] ITERATION 85 :
I0420 13:30:14.503019  6444 BendersFunctions.cpp:155]     Solving master...
I0420 13:30:16.337088  6444 Worker.cpp:108] lp_status is : 2
I0420 13:30:16.337088  6444 Worker.cpp:115] lp_status is : ORT_INFEASIBLE

The error does not occur with other solvers.

**Comment by sgatto** [comment]
It seems that this problem does not occur anymore.
I'm closing this issue for the moment
