### ISSUE TITLE
Remove the message "problem_status" : "ERROR" in the out.json file

### ISSUE THREAD

**Issue by MathildeFranconRTE** [AntaresSimulatorTeam/antares-xpansion#124]
Somewhere in the optimization part, it is hard coded that when the gap is greater than 10^-3, the variable problem_status is equal to ERROR  : 

	"solution" : 
	{
		"gap" : 94834610.000732422,
		"investment_cost" : 23806657159.173248,
		"iteration" : 144,
		"operational_cost" : 117769645781.9344,
		"overall_cost" : 141576302941.10767,
		"problem_status" : "ERROR",
		"values" : 

But the user could have chosen a gap greater than 10-3

**Comment by jmkerloch** [comment]
Currently there is 2 distinct ways to define `problem_status` depending if `benders` (sequential or mpi) or `merge_mps` is used for resolution.

For `benders` `problem_status` is `OPTIMAL` if gap is less than 1e-3. _This will be corrected with use of gap defined in user options._

For `merge_mps` `problem_status` is `OPTIMAL` depending on the status of solver problem : 
```
bool optimality_l = (status_l == operations_research::MPSolver::OPTIMAL);
```

**Should we change `merge_mps` to use gap defined in user options ?**
