### ISSUE TITLE
bendersmpiLog in case of infeasability

### ISSUE THREAD

**Issue by alhaas** [AntaresSimulatorTeam/antares-xpansion#151]
Hi everyone, when a full run ends prematurely, there is no output written to the log file. For illustration, I have attached the terminal output and the bendersmpiLog. Is this intended or can you identify an issue from the limited input provided? Do you need more information?
[out.txt](https://github.com/AntaresSimulatorTeam/antares-xpansion/files/6515346/out.txt)
[bendersmpiLog.txt](https://github.com/AntaresSimulatorTeam/antares-xpansion/files/6515348/bendersmpiLog.txt)

**Comment by sgatto** [comment]
in order to test

```c++
if [iteration>3){
exit(1)
}
```

**Comment by AbdoulbariZakir** [comment]
Hello @alhaas, i was able to repoduce the issue.
There are two things : 

1. if you want to see Benders infos (ITERATION 1 ..), like those printed in the terminal, please check the file in `your_antares_study_dir/output/lp/reportbendersmpi-0`. The philosophy of the code is to print benders steps at the same time in the standard output and in reportbendersmpi-0 file, even if benders is aborted intentionally.
2. the file name of the form `bendersmpiLog-rank0-YYYYMMDD-HHMMSS.THREADID` in `your_antares_study_dir/output/lp/` contains for now benders options and not all logs.

@sgatto, renaming files could clear up the confusion?
