### ISSUE TITLE
Numerical instability of the solver (ex: negative capacity in the master problem)

### ISSUE THREAD

**Issue by MathildeFranconRTE** [AntaresSimulatorTeam/antares-xpansion#167]
At the end of the master problem, the capacities are sometimes wrong (e.g. slightly negative) because of numerical instability of the solver, and the slave problem no longer works

Example : 
at_newdsr                                                1102.75
at_presentccgt                                                 0
be_newccgt                                                     0
be_newdsr                                                      0
be_presentgas                                                  0
be_presentgas_r                                                0
de_newdsr                                                 1112.1
de_newothnres                                                  0
fr_newdsr                                                      0
fr_presentgas                                                  0
itn_newccgt                                                    0
itn_newdsr                                                1120.7
nl_newdsr                                                      0
nl_presentccgt                                                 0
pl_newccgt                                                     0
**pl_newdsr**                                           **-1.14368e-07**
gb_newccgt                                                     0
gb_newdsr                                                9.33506

Quick fix : 
When the master solution is returned, for each capacity x and  its lower bound LB_x :
If x \in [LB_x - tol; LB_x] thenx <- LB_x
If x < LB_x - tol : Error

**Comment by jmkerloch** [comment]
After discussion with Xavier a fix can be applied when getting master solution : 

```
void WorkerMaster::get(Point & x0, double & alpha, DblVector & alpha_i) {
	x0.clear();
	std::vector<double> ptr(_solver->get_ncols());

	if (_solver->get_n_integer_vars() > 0) {
		_solver->get_mip_sol(ptr.data());
	}
	else {
		_solver->get_lp_sol(ptr.data(), NULL, NULL);
	}
	assert(_id_alpha_i.back()+1 == ptr.size());
        
        //Get lower bounds
	std::vector<double> inf_bound(_solver->get_ncols());
	_solver->get_lb(inf_bound.data(), 0, _solver->get_ncols() -1 );

        //Limit values
	double tol = 1e-4;
	for (auto const & kvp : _id_to_name) {
		x0[kvp.second] = std::max(ptr[kvp.first],inf_bound[kvp.first]);
	}
	alpha = ptr[_id_alpha];
	for (int i(0); i < _id_alpha_i.size(); ++i) {
		alpha_i[i] = ptr[_id_alpha_i[i]];
	}
}
```

**Comment by tbittar** [comment]
Plusieurs commentaires sur l'étude qui pose le problème :

1. Les coûts d'investissements sont négligeables par rapport aux coûts opérationnels, donc il faut questionner la pertinence de l'étude en elle-même.
2. Supposons qu'on veuille vraiment résoudre ce problème, à la lecture des logs, on comprend assez vite que la solution optimale et de ne pas faire d'investissement du tout. Au cours des itérations, on voit que le master (résolu avec l'option `relaxed`) essaie de nombreuses valeurs d'investissements très proches de zéro et il est très probable qu'une erreur numérique cause l'infaisabilité (par exemple ça pourrait être une résolution imprécise d'un sous-problème qui conduit à une valeur d'investissement très légèrement négative à l'itération suivante).
3. La résolution avec `master = integer` fonctionne parce qu'on ne vient pas trop près les bornes du fait que les investissements sont nécessairement des multiples de la taille de l'unité.

La question est la suivante : est-il est pertinent de mettre en place un mécanisme pour éviter ce genre d'erreurs, qui viennent ici d'une étude qui mérite d'être retravaillée point de vue métier (bien que totalement licite d'un point de vue mathématique), et sachant que la résolution avec `master = integer` fonctionne ?

**Comment by tbittar** [comment]
As for now, we only have a single example of study leading to the current issue, which can be avoided by changing the configuration of the optimizer (i.e. using `master=integer`), we do not take any action on this issue.
