### ISSUE TITLE
Specifies the solver to be used to solve master problems

### ISSUE THREAD

**Issue by MathildeFranconRTE** [AntaresSimulatorTeam/antares-xpansion#168]
Add parameter **solver** with string (two options for the moment : "Xpress" or "Cbc") in the _settings.ini_ file.

Example : 
solver = Xpress

Default value: 
solver = Cbc

**Comment by jmkerloch** [comment]
Is it OK if we change the names to : 
Xpress -> XPRESS
Cbc -> COIN
?

This will be the same name as defined in the multisolver_interface.

**Comment by MathildeFranconRTE** [comment]
Let's say that the syntax initially proposed fits better with what users are used. If it is really easier to put this new syntax, it is not dramatic.
