### ISSUE TITLE
Wrong permissions in Linux archive

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/antares-xpansion#25]
The following programs are not marked as executable
- bin/antares-8.0-solver
- xpansion-launcher/antares-xpansion-launcher

**Comment by jmkerloch** [comment]
Correction done for antares-8.0-solver but antares-xpansion-launcher is still not marked as executable

**Comment by jmkerloch** [comment]
corrected for antares-xpansion-launcher in v0.1.0-rc tag
