### ISSUE TITLE
Allow the user to choose the log level of Benders solver

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/antares-xpansion#272]
For now, in order to access the logs of the solver, the user must launch the steps of xpansion separately and modify the file `antares-study-folder/output/simulation-name/lp/options.txt` by hand to set the variable `LOG_LEVEL`.

It would be nice if the user could set the variable `LOG_LEVEL` of the Benders solver directly from `settings.ini` (similarly as `MAX_ITERATIONS` or `SOLVER_NAME`. This is particularly useful for debugging purpose.

**Comment by sgatto** [comment]
the flag can be named `solver_log_level`
