### ISSUE TITLE
Release date of 0.6.0 ?

### ISSUE THREAD

**Issue by ValentinSatge** [AntaresSimulatorTeam/antares-xpansion#285]
Hello,

I am not sure to be on the right place, if so i am sorry but I could not find any other way to have this info.
I am currently working with Xpansion and just downloaded the 8.1 version.  In one "close issue", it is said that Xpansion can only work with 8.1 if we get the 0.6.0 release. 
Is it possible to have an order of magnitude of the release date ? In a week, a month, next year... to know if i need to go back to the old version. 

Thanks for the answer 

Valentin

**Comment by tbittar** [comment]
Hello Valentin,

Xpansion will indeed only work with Antares 8.1 in the 0.6.0 release, which should available in about a week or so,

Thomas
