### ISSUE TITLE
Integration with AntaresWeb: add option for study update to provide command list

### ISSUE THREAD

**Issue by sgatto** [AntaresSimulatorTeam/antares-xpansion#296]
to be detailed:
The xpansion study-update could produce the list of commands for AntaresWeb to generate à variant of the original study

**Comment by tbittar** [comment]
A reflexion on the whole usage of the toolsuit should be done

**Comment by tbittar** [comment]
We should ask the user if they use the output of study update (folder updated links in AntaresWeb)
