### ISSUE TITLE
Interaction between the different version of Antares

### ISSUE THREAD

**Issue by MathildeFranconRTE** [AntaresSimulatorTeam/antares-xpansion#30]
Interaction between the version of Antares used in the study (7.0.0 in the provided example) and the Antares 8.0.0 executable present in the Xpansion package ?

**Comment by jmkerloch** [comment]
Related to https://github.com/AntaresSimulatorTeam/Antares_Simulator/issues/117

8.0.0-rc1 solver accept previous version of study.
Need to : 
[ ] updgrade example study to 8.0.0
[ ] use 8.0.0-rc2 (not available yet)
