### ISSUE TITLE
Unable to run sequential and mpi tests in parallel

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/antares-xpansion#303]
Since `medium` tests have been split in `medium_sequential` and `medium_parallel`, launching `ctest -j 8 -L medium` can cause that an Antares-Xpansion optimization is launched twice on the same Antares study, which leads to a crash (either by the locker or the fact that some files are missing).

We need to find a way to say to `ctest` not to execute `medium_sequential` and `medium_mpi` in parallel.

**Comment by a-zakir** [comment]
solved in 0.6.0-rc1
