### ISSUE TITLE
Bug avec le paramètre include-trace dans le generalsettings.ini d'Antares

### ISSUE THREAD

**Issue by MathildeFranconRTE** [AntaresSimulatorTeam/antares-xpansion#31]
Xpansion et Antares plantent lorsqu'il y a le paramètre
_include-trace_ 
dans le settings/generaldata.ini d'Antares.

Dans le log Antares : 

[Thu Jan 21 19:58:29 2021][solver][warns] D:\Users\antaresXpansion\test_case_7_0_new_version\settings\generaldata.ini: 'include-trace': Unknown property
[Thu Jan 21 19:58:29 2021][solver][error] Found 1 warning: The simulation must stop.

Dans le log Xpansion :  

D:\Users\antaresXpansion\Opensource\antaresXpansion-0.1.0-win64\xpansion-launcher>antares-xpansion-launcher.exe  --step full --dataDir D:\Users\antaresXpansion\test_case_7_0_new_version --installDir D:\Users\antaresXpansion\Opensource\antaresXpansion-0.1.0-win64\bin\ --method mpibenders
['semibase', 'peak', 'pv', 'battery', 'transmission_line']
starting mps generation
-- pre antares
-- launching antares
['D:\\Users\\antaresXpansion\\Opensource\\antaresXpansion-0.1.0-win64\\bin\\antares-8.0-solver.exe', 'D:\\Users\\antaresXpansion\\test_case_7_0_new_version']
WARNING: exited antares with status 1
['20210121-1936eco', '20210121-1941eco', '20210121-1943eco', '20210121-1952eco', '20210121-1958eco', 'maps']
['20210121-1936eco', '20210121-1941eco', '20210121-1943eco', '20210121-1952eco', '20210121-1958eco', '20210121-1958eco-2', 'maps']
-- post antares
Traceback (most recent call last):
  File "launch.py", line 11, in <module>
  File "antares_xpansion\driver.py", line 219, in launch
  File "antares_xpansion\driver.py", line 489, in generate_mps_files
  File "antares_xpansion\driver.py", line 343, in post_antares
  File "antares_xpansion\driver.py", line 370, in get_names
AssertionError
[16752] Failed to execute script launch

Ce paramètre ne sert peut-être plus maintenant, mais il était présent dans les précédentes versions de la nouvelle version d'Xpansion. Il faudrait que cela ne fasse au moins pas planter l'outil.

**Comment by jmkerloch** [comment]
We need to remove this parameters from `generaldata.ini`.
@MathildeFranconRTE  could you provide us the study used ?
