### ISSUE TITLE
create output writer interface

### ISSUE THREAD

**Issue by a-zakir** [AntaresSimulatorTeam/antares-xpansion#327]
in order to harmonize benders outputs, create an (class) interface (OutputWriter) inherited by the actual JsonWriter class.

- the JsonWriter class will be used by the Sequential benders and by the master proc (world.rank =0) of Mpi benders.
-  a "void" class (voidWriter) that write nothing has to derive from OutputWriter if world.rank !=0.

**Comment by sgatto** [comment]
linked to #251
