### ISSUE TITLE
Different "Optimal portfolio" in out_solutionmaster and in log

### ISSUE THREAD

**Issue by ABurlin** [AntaresSimulatorTeam/antares-xpansion#372]
Hello,

The optimal portfolio (best iteration) found in Xpansion log or in "user\xpansion\temp\in_z0" is not the same as the one given by "out_solutionmaster". Why is there a difference and which one should I choose ?

Thank you,

Arthur

**Comment by sgatto** [comment]
@tbittar or @MathildeFranconRTE  can answer in more details.
We think this issue refers to the ancient R-verion of the AntaresXpansion https://github.com/rte-antares-rpackage/antaresXpansion

**Comment by tbittar** [comment]
This is a known issue of the no longer maintained R version of Antares-Xpansion and appropriate support has been given to the user. As this question does not involve the current code, I close this issue.
