### ISSUE TITLE
Remove empty `constraints-xxx-.txt` files after Antares step

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/antares-xpansion#398]
After the Antares step, the study output cleaner should remove the constraints files as they are not used (check if this is true)

**Comment by JasonMarechal25** [comment]
If we're talking about the files in output directory then they are cleaned up by the lpnamer step. A quick search of "constraints" reveal usage of "additionnal constraints" in lpnamer.
As of now I lack visibility to cleanup files after antares step. We may discuss this to issue to ensure that we are aligned on the files discussed

**Comment by tbittar** [comment]
The file `constraints.txt` is used to store the mapping between constraints ids and constraints names in Antares-Simulator. For now, as the constraints are not named within Antarse-Simulator, this file is useless. A work is in progress to directly name the constraints and variables in the mps files that are generated by Antares-Simulator, that will remove the need for `contraints.txt` and `variables.txt` files. No further action is required within Xpansion.
