### ISSUE TITLE
Xpansion fails when no solver is specified in `settings.ini`

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/antares-xpansion#410]
When no solver is given in `settings.ini`, we expect xpansion to use the default `Cbc` solver. However, even though a message states that `Cbc` is used, Xpansion fails later on with the message `Solver ' ' not available`.

The problem probably comes from the function https://github.com/AntaresSimulatorTeam/antares-xpansion/blob/71cfdea92810c698ecc3d94bc48ca561334d0e6c/src/python/antares_xpansion/xpansion_study_reader.py#L29-L40 that should replace an empty solver string with `Cbc` similarly as what is done in https://github.com/AntaresSimulatorTeam/antares-xpansion/blob/71cfdea92810c698ecc3d94bc48ca561334d0e6c/src/python/antares_xpansion/xpansion_study_reader.py#L73-L86

**Comment by a-zakir** [comment]
Hello, thanks for the issue, the problem is in the data type after the "=" in the settings.ini file. Even if solver is set to = "Cbc", that will raise an exception. We expect to read a string without quotes. 
We can discuss  about how options are expected to be like.
