### ISSUE TITLE
generate default settings.ini

### ISSUE THREAD

**Issue by a-zakir** [AntaresSimulatorTeam/antares-xpansion#413]
to avoid certains erros while writing the settings.ini, it can be useful to provide a tool (python script, or a pre-step for Xpansion) that generate all default parameters.

**Comment by tbittar** [comment]
The idea is interesting, but needs further thinking. If we follow this path, we should maybe consider to write a library in order not only to create a default settings file, but also a candidate file and more importantly to be able to modify efficiently a candidates file with a large number of candidate. For example we want to be able to modify the investment cost of many candidates efficiently.
