### ISSUE TITLE
method option in settings.ini

### ISSUE THREAD

**Issue by a-zakir** [AntaresSimulatorTeam/antares-xpansion#414]
in some examples(see `examples/SmallTestFiveCandidates/user/expansion/settings.ini`), `method = benders_decomposition` option is given.
Since the benders method has to be set as a command line option, it is not necessary to keep it in settings.ini
Also some checks are done with wrong default value to =="benders_decomposition" in python code.

**Comment by tbittar** [comment]
Yes this option comes from the R version of Xpansion and should be removed from `settings.ini`
