### ISSUE TITLE
Improve communication with users

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/antares-xpansion#432]
Some user tends to do studies that are wrongly formatted (from a business point of view) or studies that try to solve the wrong problem.
This cost a lot of time lost for everyone: users that need to redo the study properly, PO that need to analyse the study and devs that need to check if bugs did occur.

It would be good to improve communication with users before the start of the study.

Suggestions:
- Add information in messages in how to contact the team (maybe why and when)
- Directly contact users pre-emptively to inform them that we can help them to construct studies

**Comment by flomnes** [comment]
antares-xpansion is still young, I would add another suggestion : organize training sessions internally for new users.
