### ISSUE TITLE
Add --version option to antares-xpansion-launcher

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/antares-xpansion#472]
Currently, it is impossible to know the version of xpansion.

### Current output

```bash
[mco-antares@calinfrprdif201vm xpansion]$ ./antares-xpansion-launcher --version
usage: antares-xpansion-launcher [-h]
                                 [--step {full,antares,getnames,lp,optim,update}]
                                 [--simulationName SIMULATIONNAME] -i DATADIR
                                 [--installDir INSTALLDIR]
                                 [-m {mpibenders,mergeMPS,sequential}]
                                 [-n N_MPI] [--keepMps]
antares-xpansion-launcher: error: the following arguments are required: -i/--dataDir
```

### Option parser
https://github.com/AntaresSimulatorTeam/antares-xpansion/blob/5d4a2800c9bbcb6ca54b993aaaa70840d94864c2/src/python/antares_xpansion/input_parser.py#L62-L69

The output is a bit contradictory with the option parser : the option seems to be handled, but it's not.

**Comment by a-zakir** [comment]
Hi,
tested with antares-xpansion 0.6.0 and 0.7.0:
`s15118@WD0564 MINGW64 ~/Downloads/antaresXpansion-0.6.0-windows-single-file
$ ./antares-xpansion-launcher.exe --version
0.6.0

s15118@WD0564 MINGW64 ~/Downloads/antaresXpansion-0.6.0-windows-single-file
$ ./antares-xpansion-launcher.exe -v
0.6.0`

`s15118@WD0564 MINGW64 ~/Downloads/antaresXpansion-0.7.0-windows-single-file
$ ./antares-xpansion-launcher.exe -v
0.7.0

s15118@WD0564 MINGW64 ~/Downloads/antaresXpansion-0.7.0-windows-single-file
$ ./antares-xpansion-launcher.exe --version
0.7.0
`

From the description of available steps  `[--step {full,antares,**getnames,lp,optim,update**}]`, i guess the version of xpansion you were testing is <0.6.0 which could explain the problem. The version display option was introduced in v0.6.0.
