### ISSUE TITLE
Upgrade Antares-Simulator version to 8.3.1

### ISSUE THREAD

**Issue by a-zakir** [AntaresSimulatorTeam/antares-xpansion#506]
to upgrade antares version (to 8.3.1)  make sure that (non-exhaustive list) : 

- newly added options are handled
- adequacy patch-options  are deactivated in Xpansion run.
- +/- infinity in binding constraint RHS are compatible with coin solvers (problem_generation step)

**Comment by tbittar** [comment]
If the adequacy patch is activated in the Antares study, Xpansion should behave as follows:
- Copy the `generaldata.ini` file and deactivate the adequacy patch for the Xpansion run
- Print a warning to inform the user that the adequacy is ignored in Xpansion
- (Delete the Xpansion copy of the `generaldata.ini` file after the antares step?)

**Comment by JasonMarechal25** [comment]
Verify that Xpansion can read Simulator output if xpress is used for Simulator
Ensure that we use Xpress for Simulator in Antares step

**Comment by tbittar** [comment]
Closed by PR #517
