### ISSUE TITLE
Add & use python binding for lpnamer and benders[mpi,sequential]

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/antares-xpansion#83]
# Summary

Several executables are called iteratively. They mainly communicate through files. This approach has two drawbacks :
- Need for many disk read/writes, which are possibly slow
- Rounding errors when reading/writing floats

This could be solved by turning these executables into python modules (libraries). Many frameworks exist to allow this kind of binding. One of them is [pybind11](https://github.com/pybind/pybind11).

The idea would be to expose a minimal number of classes and functions to python : whatever is needed to communicate between these executables.

The python script would look like this 

```python
import lpnamer
import benders

my_constraints = lpnamer.constraints(...)
my_lp = lpnamer.lp_namer(config_path, lpnamer.relaxed, constraints)

while gap > threshold:
    benders.run(...)

```

In the following, we make a list of I/O of lpnamer, benders, etc. that could fall into the scope of this work.

# lpnamer
## Input
usage: <exe> <Xpansion study output> <relaxed or integer> <path to exlusions file>
- xpansion study output => **keep path**
- optimization strategy : relaxed/integer => **py enum**
- additional constraints / exclusion files => **Turn into py object**
   
## Output
Variable correspondence written into "lp" files.

```cpp
std::map<std::string, std::map<std::string, int> > output;
// ...
output["master"][name] = i;
// ...
for (auto const & mps : output) {
	for (auto const & pmax : mps.second) {
		coupling_file << std::setw(50) << mps.first;
		coupling_file << std::setw(50) << pmax.first;
		coupling_file << std::setw(10) << pmax.second;
		coupling_file << std::endl;
	}
}
```

# benders[mpi,sequential]
## Input
Config file loaded into `BendersOptions` object
## Output
JSON files containing the optimization results, among other things.

## Merge/analyse MPS ?

**Comment by flomnes** [comment]
Another solution could be to turn benders and lp_namer into libraries whose functions would be called in the same executable. Comments are welcome.

**Comment by sgatto** [comment]
I'm closing this issue because we don't see how to implement a Python binding for an MPI program.

Further investigations are needed
