### ISSUE TITLE
Make lp directory self-contained to run outer_loop exe on this directory

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/antares-xpansion#857]
Currently, we can launch Benders from an lp directory using `benders options.json`

We expect to have the same behavior with outer_loop, however, it uses an additional input file in the study, which is not in the lp directory (`outer_loop.yml`)

The lp directory should contain all necessary information to launch the outer loop with `outer_loop options.json`.

A solution could be to copy `outer_loop.yml` in the lp directory, but there might be a more clever way ?

**Comment by a-zakir** [comment]
the yml file can be placed inside the lp dir

**Comment by a-zakir** [comment]
make sure to do in options.json :
"OUTER_LOOP_OPTION_FILE": "outer_loop.yml"
