### ISSUE TITLE
Add yearly-weights parameter

### ISSUE THREAD

**Issue by MathildeFranconRTE** [AntaresSimulatorTeam/antares-xpansion#92]
### Description of the parameter

**yearly-weights** offers the possibility of assuming that the Monte Carlo years simulated in the ANTARES study are not equally probable. The most representative years may be given greater weight than those that are less representative. The yearly-weights points to a vector _(ω_1,…,ω_n )_, with _n_ the number of Monte-Carlo years in the study, which is used to evaluate the expected production costs.
![image](https://user-images.githubusercontent.com/31503237/112161104-17ee4a00-8beb-11eb-9bc3-0618cc59a0fd.png)
With _cost_i_ the production cost of the _i-th_ Monte Carlo year.

### Developments

--> Add the **yearly-weights**  parameter in the _settings.ini_ file in the _user/expansion/ folder_.
--> This is not a mandatory parameter, it may not appear in the settings.ini (as the _additional-constraints_ parameter), therefore empty by default
--> Assert that the value filled is a string specifying the name of a file
--> Assert that this file exists, is located in the _user/expansion/ folder_ of the ANTARES study. 
--> Read and assert that this file contains one column with numerical values (double) 
![image](https://user-images.githubusercontent.com/31503237/112166927-5cc8af80-8bf0-11eb-8de4-14b0454c86f6.png)
--> Assert that  (all(yearly_weights >= 0))
--> Assert that (sum(yearly_weights) > 0)
--> Assert that the length of the column is equal to the number of Monte-Carlo years in the ANTARES study (the value of the i-th row is the weight of the i-th Monte Carlo year)
      If there is a playlist in the study, assert that length(yearly_weights) == length(antares::playlist) and read the weights
      If there is no playlist in the study, assert that length(yearly_weights) == length(antares::nbyears) and read the weights
      Else stop("Number of yearly weights does not correspond to number of MC years in the Antares study")
Warning : it is up to the user to check the coherence between the weights and the Monte carlo years in the Antares study !
--> If a weight is egal to 0 : don't modify the Antares playlist (MPS of this file are thus generated) and try to modify the _lp_namer_ so that the year does not appear in the structure.txt and is not taken into account in the in the optimization block.
--> Create a _weights.txt_ file in the same location as the _structure.txt_ file and with a similar structure with two columns :
         Add one line per sub-problem (so per year and per week) : in the first column add the name of the mps problem (as in the _structure.txt_ file) and in the second column, repeat the weight of the year
         Add an extra line with the name WEIGHT_SUM and the sum of the weights

![image](https://user-images.githubusercontent.com/31503237/112173844-386fd180-8bf6-11eb-8bc6-9c818a52d0ba.png)

--> Edit the SLAVE_WEIGHT parameter in the _options.txt_ file ( _/lp/_ folder) with weights.txt instead of CONSTANT :
                  SLAVE_WEIGHT                   weights.txt                
-->Take into account Xavier's pull request for the optimization
https://github.com/AntaresSimulatorTeam/antares-xpansion/pull/91

Example study to test  :
[xpansion-test-01-weights.zip](https://github.com/AntaresSimulatorTeam/antares-xpansion/files/6190960/xpansion-test-01-weights.zip)

**Comment by jmkerloch** [comment]
Some questions : 

- How are the .mps file indicated in the created `weight.txt` ?

with suffix : 
```
problem-1-1-AAAAMMDD-hhmmss.mps 1
problem-1-2-AAAAMMDD-hhmmss.mps 1
problem-1-24-AAAAMMDD-hhmmss.mps 1
```

without suffix : 
```
problem-1-1-AAAAMMDD-hhmmss 1
problem-1-2-AAAAMMDD-hhmmss 1
problem-1-24-AAAAMMDD-hhmmss 1
```

- What order should be used for .mps listing ? same order as the mps.txt file created for lp_namer ?

**Comment by Blaxav** [comment]
They're indicated without suffix, you have an example in ```data_test\mini_network/slave_weights.txt```.

The order doesn't matter, as you can see in ```BendersOptions.cpp:82```, the weights are read in a ```std::map<std::string,double>```, where the key is the name of the problem.

**Comment by jmkerloch** [comment]
@MathildeFranconRTE  there is some python code that support `yearly_weights` option but not `yearly-weights`.

Can you confirm `yearly-weights` must be used ?

**Comment by MathildeFranconRTE** [comment]
Yes, I confirm yearly-weights

**Comment by jmkerloch** [comment]
We're doing some refactoring so there is no problem for changing the name.
