### ISSUE TITLE
create logger module for benders

### ISSUE THREAD

**Issue by jmkerloch** [AntaresSimulatorTeam/antares-xpansion#93]
Currently `std::cout` is used to display some information to user during optimisation.

We need to introduce a logger module so `std::cout` can display different information if we are using antares-xpansion as a user or as a developper.

This logger should also be able to add log to a log file.

**Comment by jmkerloch** [comment]
For this feature we need to : 

- [ ] create an abstract class `XpansionLogger` defining an interface for the different log steps : 
- current options
- current iteration investment candidate
- current iteration solution
- last solution

- [ ]  add some generic log in the interface : 
- trace
- debug
- info
- warning
- error

- [ ]  implement interface in 4 or more classes : 
- `FileLogger` : add log in a log file
- `StdCoutLogger `: display log in `std::cout`
- `DevLogger `: create log for developper use. Need a list of `XpansionLogger` which will be used for log. Default logger used are `FileLogger` and `StdCoutLogger`.
- `UserLogger `: display information in `std::cout` for user. Use also a `DevLogger `but only with one `FileLogger`

**Comment by flomnes** [comment]
Possible implementation

```cpp
#include <iostream>
#include <fstream>
// Data to be logged
struct Data {
  int a;
};

// Interface class
class ILog {
public:
  virtual void output(const Data& d) = 0;
};

// Solver function that has to write data
void solver(ILog& log) {
  Data d{a:2};
  log.output(d);
}

// Log to file
class FLog : public ILog {
public:
  FLog(const char* path) : os{path} {}
  virtual void output(const Data& d) override final {
    os << d.a << std::endl;
  }
protected:
  std::ofstream os;
};

// Log to stream
class SLog : public ILog {
public:
  SLog(std::ostream& os) : os(os) {}
  virtual void output(const Data& d) override final {
    os << d.a << std::endl;
  }
protected:
  std::ostream& os;
};

// Use callback function
class CbLog : public ILog {
public:
  CbLog(void (*cb)(const Data&)) : cb(cb) {}
  virtual void output(const Data& d) override final {
    cb(d);
  }
protected:
  void (*cb)(const Data&);
};

// Test :)
int main() {
  FLog file_out("file_output.dat");
  auto v = solver; // Function alias
  v(file_out);

  SLog std_out(std::cout);
  v(std_out);

  SLog std_err(std::cerr);
  v(std_err);

  std::ofstream f("stream_output.dat");
  SLog std_file(f);
  v(std_file);

  CbLog cb_log([](const Data& d) {
                 std::cout << "cb " << d.a << std::endl;
               });
  v(cb_log);
}
```

**Comment by klorel** [comment]
That's the idea. 

I assume that 4 "output" method will be in the interface (each dedicated to the step described by @jmkerloch), to be checked.

What should be the Data struct?

**Comment by klorel** [comment]
That's the idea.

I assume that 4 "output" method will be in the interface (each dedicated to the step described by @jmkerloch), to be checked.

What should be the Data struct?

Also, how to handle multiple loggers (file and standard output)?

**Comment by flomnes** [comment]
We could have two interfaces :

- As above, **where** to write data (file, stream, callback)
- What data needs to be written : "user" or "debug" 

To write data to multiple destinations, we could have an interface like
```cpp
enum Format {
    User,
    Debug
};

addLoger(ILog& logger, Format format); 
```

Or alternatively keep the format in the ILog class as a private member

```cpp
// Interface class
class ILog {
public:
  virtual void output(const Data& d) = 0;
private:
   Format fmt;
};
```

In my opinion the `Data` struct should contain as much info as possible, letting the logger pick what to write and how.

**Comment by klorel** [comment]
I don't get it, sorry.

To have all needed  features, the base class should look like :
```
// Interface class
class ILog {
public:
   typedef std::shared_ptr<ILog> Ptr;
public:
  void call_log_at_initialization(const Data& d){
    for(auto const & i : _others){
      i->log_at_initialization(d);
    }
  }
  void call_log_at_iteration      (const Data& d){ // same idea as above}
  void call_log_at_ending        (const Data& d){ // same idea as above}
  void push_back(Ptr ptr){_others.push_back(Ptr))
protected:
  virtual void log_at_initialization(const Data& d) = 0;
  virtual void log_at_iteration      (const Data& d) = 0;
  virtual void log_at_ending        (const Data& d) = 0;

  std::list<Ptr > _others;
};
```

With this design, we can add any number of logger and mix User/Research/etc. Printing the solution and/or the candidates values are delegated to the log_at_iteration for example.

**Comment by flomnes** [comment]
After some discussions with @klorel, here is what I suggest

```cpp
#include <memory>
#include <list>

// Data to log
struct Data {
  int field1;
  float field2;
};

// Interface class
class ILog {
public:
  virtual void log_at_initialization(const Data& d) = 0;
  virtual void log_at_iteration      (const Data& d) = 0;
  virtual void log_at_ending        (const Data& d) = 0;
};

class MasterLog : public ILog {
private:
  std::list<std::shared_ptr<ILog>> logs;
public:
  virtual ~MasterLog() {}
  void addLogger(std::shared_ptr<ILog> log) {
    logs.push_back(log);
  }
  virtual void log_at_initialization(const Data& d) override {
    for (auto& log : logs)
      log->log_at_initialization(d);
  }
  virtual void log_at_iteration(const Data& d) override {
    // ...
  }
  virtual void log_at_ending (const Data& d) override {
    // ...
  }
};

#include <iostream>
#include <fstream>

class LogUser : public ILog {
public:
  LogUser(std::ofstream&& file_out, std::ostream& console_out) : file_out(std::move(file_out)), console_out(console_out) {
  }
  virtual void log_at_initialization(const Data& d) override {
    file_out << "field1=" << d.field1 << std::endl;
    console_out << "field2=" << d.field2 << std::endl;
  }
  virtual void log_at_iteration(const Data& d) override {
    // ...
  }
  virtual void log_at_ending (const Data& d) override {
    // ...
  }
private:
  std::ofstream file_out;
  std::ostream& console_out;
};

class LogExpert : public ILog {
public:
  virtual void log_at_initialization(const Data& d) override {
    // ...
  }
  virtual void log_at_iteration(const Data& d) override {
    // ...
  }
  virtual void log_at_ending (const Data& d) override {
    // ...
  }
};

void run(MasterLog& m) {
  Data d{field1:21, field2:332.4f};
  m.log_at_initialization(d);
  for (int i = 0; i < 5; i++)
      m.log_at_iteration(d);
  m.log_at_ending(d);
}

int main() {
  MasterLog masterLog;
  masterLog.addLogger(std::make_shared<LogUser>(std::ofstream("log.txt"),
                                                std::cout));
  masterLog.addLogger(std::make_shared<LogExpert>());
  run(masterLog);
}
```
@Blaxav does that fit your purposes ?

**Comment by klorel** [comment]
@flomnes , with LogUser having only a std::ostream& as an attribute, you can easily go to an implementation allowing : 
```
  MasterLog masterLog;
  masterLog.addLogger(std::make_shared<LogUser>(std::ofstream("log.txt"));
  masterLog.addLogger(std::make_shared<LogUser>(std::cout));
  masterLog.addLogger(std::make_shared<LogExpert>());
  run(masterLog);
```

**Comment by flomnes** [comment]
@klorel Indeed, class `LogUser` can be splitted. However, it seems that for users, we want to log different information in the console and in files.

So following your remark, we would have
```cpp
MasterLog masterLog;
masterLog.addLogger(std::make_shared<LogUserFile>(std::ofstream("log.txt"));
masterLog.addLogger(std::make_shared<LogUserConsole>(std::cout));
masterLog.addLogger(std::make_shared<LogExpert>());
run(masterLog);
```

Is that right ?

**Comment by flomnes** [comment]
Note : `Data` is an alias for `BendersData`, which contains all the data to be logged. Therefore, there is no need to create a new class.

**Comment by klorel** [comment]
@flomnes yes, if this behavior is needed, we need 2 implementations.

Regarding Data, ok, but it has to be checked if this class (Benders Data) is really the one used to print everything.

Just need @Blaxav to amend/comment all of this :)

**Comment by sgatto** [comment]
I might seem pedantic but we could even have 3 types of dataStructures for each type of output
`BeginningData` `IterationData` `FinalData`

**Comment by sgatto** [comment]
I like the idea in general, thanks

**Comment by Blaxav** [comment]
@klorel, Yes I checked yesterday, BendersData contains and is used to print everything.

@sgatto I don't know if doing three different dataStructures would be relevant. For example, the best candidate solution seen during optimisation, "bestx" for now, would be used in FinalData for solution print, and can be used in the optimization process at each iteration (in stabilization methods). Then this vector should be copied two times each time it is modified. If we want to tidy up things, maybe we could have a BendersData which contains everything, and BeginningData, IterationData and FinalData would contain only pointers on relevant datas in BendersData.
